"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from klarna import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Options:
    
    color_border: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_border'), 'exclude': lambda f: f is None }})
    r"""Color for the border of elements within the iFrame. Value should be a CSS hex color, e.g. \\"#FF9900\\" """  
    color_border_selected: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_border_selected'), 'exclude': lambda f: f is None }})
    r"""Color for the border of elements within the iFrame when selected by the customer. Value should be a CSS hex color, e.g. \\"#FF9900\\" """  
    color_details: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_details'), 'exclude': lambda f: f is None }})
    r"""Color for the bullet points within the iFrame. Value should be a CSS hex color, e.g. \\"#FF9900\\" """  
    color_text: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_text'), 'exclude': lambda f: f is None }})
    r"""Color for the texts within the iFrame. Value should be a CSS hex color, e.g. \\"#FF9900\\" """  
    radius_border: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('radius_border'), 'exclude': lambda f: f is None }})
    r"""Radius for the border of elements within the iFrame."""  
    